"use client";

import React from 'react';
import { useRouter } from 'next/navigation';
import { format } from 'date-fns';
import { ClipboardList, ChevronRight, AlertCircle, Clock, CheckCircle2, XCircle, FileDown, Eye, Trash2, Printer, Edit2 } from 'lucide-react';
import * as XLSX from 'xlsx';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { deleteRequisitionAction } from '@/inventory/api/controller';

interface Requisition {
    id: string;
    requisitionNumber: string;
    date: Date | string;
    status: 'PENDING' | 'APPROVED' | 'REJECTED' | 'FULFILLED' | 'CANCELLED';
    priority: 'LOW' | 'NORMAL' | 'HIGH' | 'URGENT';
    branch: { name: string };
    user: { name: string };
    items: { productName: string, quantity: number, sku?: string }[];
}

interface RequisitionListProps {
    requisitions: Requisition[];
    onRefresh?: () => void;
}

export const RequisitionList: React.FC<RequisitionListProps> = ({ requisitions, onRefresh }) => {
    const router = useRouter();
    const [selectedReq, setSelectedReq] = React.useState<Requisition | null>(null);

    const handleExportExcel = () => {
        const exportData = requisitions.map(req => ({
            'Requisition #': req.requisitionNumber,
            'Branch': req.branch.name,
            'Requester': req.user.name,
            'Priority': req.priority,
            'Status': req.status,
            'Date': format(new Date(req.date), 'yyyy-MM-dd HH:mm'),
            'Items': req.items.map(i => `${i.productName} (${i.quantity})`).join('; ')
        }));

        const ws = XLSX.utils.json_to_sheet(exportData);
        const wb = XLSX.utils.book_new();
        XLSX.utils.book_append_sheet(wb, ws, "Requisitions");
        XLSX.writeFile(wb, `requisitions_bulk_${format(new Date(), 'yyyyMMdd_HHmm')}.xlsx`);
    };

    const handleExportPdf = () => {
        const doc = new jsPDF();
        doc.setFontSize(22);
        doc.setTextColor(79, 70, 229);
        doc.text("GONZA SYSTEMS - REQUISITIONS REPORT", 14, 20);
        doc.setFontSize(10);
        doc.setTextColor(100);
        doc.text(`Generated on: ${format(new Date(), 'PPPP')}`, 14, 26);

        const tableData = requisitions.map((req, idx) => [
            idx + 1,
            req.requisitionNumber,
            req.branch.name,
            req.priority,
            req.status,
            format(new Date(req.date), 'yyyy-MM-dd')
        ]);

        autoTable(doc, {
            startY: 35,
            head: [['#', 'Req Number', 'Branch', 'Priority', 'Status', 'Date']],
            body: tableData,
            theme: 'striped',
            headStyles: { fillColor: [79, 70, 229] }
        });

        doc.save(`requisitions_report_${format(new Date(), 'yyyyMMdd')}.pdf`);
    };

    const generateRequisitionPDF = (req: Requisition) => {
        const doc = new jsPDF();

        // Header
        doc.setFontSize(22);
        doc.setTextColor(79, 70, 229); // Primary color
        doc.text("GONZA SYSTEMS", 14, 20);
        doc.setFontSize(10);
        doc.setTextColor(100);
        doc.text("Inventory Requisition Document", 14, 26);

        // Requisition Details
        doc.setDrawColor(230);
        doc.line(14, 30, 196, 30);

        doc.setFontSize(12);
        doc.setTextColor(0);
        doc.text(`REQ NUMBER: ${req.requisitionNumber}`, 14, 40);
        doc.setFontSize(10);
        doc.text(`Status: ${req.status}`, 14, 46);
        doc.text(`Priority: ${req.priority}`, 14, 52);

        doc.text(`Branch: ${req.branch.name}`, 140, 40);
        doc.text(`Date: ${format(new Date(req.date), 'MMM dd, yyyy')}`, 140, 46);
        doc.text(`Requested By: ${req.user.name}`, 140, 52);

        // Items Table
        autoTable(doc, {
            startY: 60,
            head: [['#', 'Product Name', 'SKU', 'Quantity']],
            body: req.items.map((item, idx) => [
                idx + 1,
                item.productName,
                item.sku || 'N/A',
                item.quantity
            ]),
            theme: 'striped',
            headStyles: { fillColor: [79, 70, 229] },
            styles: { fontSize: 9 }
        });

        // Footer
        const finalY = (doc as any).lastAutoTable.finalY + 10;
        doc.setFontSize(8);
        doc.setTextColor(150);
        doc.text("Note: This document is an official stock request generated by the Gonza Inventory Management System.", 14, finalY);

        doc.save(`REQUISITION_${req.requisitionNumber}.pdf`);
    };

    const handleDelete = async (id: string) => {
        if (!confirm("Are you sure you want to delete this requisition? This action cannot be undone.")) return;
        const res = await deleteRequisitionAction(id);
        if (res.success) {
            if (onRefresh) onRefresh();
        } else {
            alert("Failed to delete: " + res.error);
        }
    };

    if (requisitions.length === 0) {
        return (
            <div className="text-center py-20 bg-card border border-border rounded-[3rem] border-dashed">
                <ClipboardList className="w-12 h-12 mx-auto text-muted-foreground opacity-30 mb-4" />
                <h4 className="text-xl font-black italic text-muted-foreground opacity-60">No Requisitions Found</h4>
                <p className="text-xs text-muted-foreground font-medium mt-2">Create your first stock request to get started.</p>
            </div>
        );
    }

    return (
        <div className="space-y-4">
            <div className="flex justify-end gap-3">
                <button
                    onClick={handleExportExcel}
                    className="flex items-center gap-2 px-4 py-2 bg-muted hover:bg-muted/80 text-[10px] font-black uppercase tracking-widest rounded-xl transition-all border border-border"
                >
                    <FileDown className="w-4 h-4 text-emerald-500" />
                    Download Bulk Excel
                </button>
                <button
                    onClick={handleExportPdf}
                    className="flex items-center gap-2 px-4 py-2 bg-muted hover:bg-muted/80 text-[10px] font-black uppercase tracking-widest rounded-xl transition-all border border-border"
                >
                    <FileDown className="w-4 h-4 text-rose-500" />
                    Download Bulk PDF
                </button>
            </div>
            <div className="bg-card border border-border rounded-[2.5rem] overflow-x-auto shadow-sm">
                <table className="w-full text-left font-sans min-w-[900px]">
                    <thead>
                        <tr className="bg-muted/30 border-b border-border">
                            <th className="px-8 py-5 text-[10px] font-black uppercase tracking-widest text-muted-foreground">Requisition Details</th>
                            <th className="px-6 py-5 text-[10px] font-black uppercase tracking-widest text-muted-foreground">Contents</th>
                            <th className="px-6 py-5 text-[10px] font-black uppercase tracking-widest text-muted-foreground">Priority</th>
                            <th className="px-6 py-5 text-[10px] font-black uppercase tracking-widest text-muted-foreground">Status</th>
                            <th className="px-8 py-5 text-right text-[10px] font-black uppercase tracking-widest text-muted-foreground">Actions</th>
                        </tr>
                    </thead>
                    <tbody className="divide-y divide-border/50">
                        {requisitions.map((req) => (
                            <tr key={req.id} className="hover:bg-muted/10 transition-colors group">
                                <td className="px-8 py-5">
                                    <div className="flex flex-col">
                                        <span className="font-black text-sm text-foreground">{req.requisitionNumber}</span>
                                        <span className="text-[10px] text-muted-foreground font-bold uppercase truncate max-w-[150px] flex items-center gap-1.5 mt-0.5">
                                            <AlertCircle className="w-3 h-3 text-primary/40" />
                                            {req.branch.name} • {req.user.name}
                                        </span>
                                    </div>
                                </td>
                                <td className="px-6 py-5">
                                    <div className="flex flex-col gap-1">
                                        <span className="text-sm font-bold text-foreground/80">{req.items.length} Product Types</span>
                                        <span className="text-[10px] text-muted-foreground font-bold italic truncate max-w-[200px] uppercase tracking-wider opacity-60">
                                            {req.items.slice(0, 2).map(i => i.productName).join(', ')}
                                            {req.items.length > 2 && '...'}
                                        </span>
                                    </div>
                                </td>
                                <td className="px-6 py-5">
                                    <PriorityBadge priority={req.priority} />
                                </td>
                                <td className="px-6 py-5">
                                    <StatusBadge status={req.status} />
                                </td>
                                <td className="px-8 py-5 text-right">
                                    <div className="flex items-center justify-end gap-1">
                                        <button
                                            onClick={() => setSelectedReq(req)}
                                            className="p-2 hover:bg-primary/10 rounded-xl transition-all text-muted-foreground hover:text-primary"
                                            title="View Details"
                                        >
                                            <Eye className="w-4 h-4" />
                                        </button>
                                        <button
                                            onClick={() => router.push(`/inventory/requisitions/${req.id}/edit`)}
                                            className="p-2 hover:bg-blue-500/10 rounded-xl transition-all text-muted-foreground hover:text-blue-600"
                                            title="Edit Request"
                                        >
                                            <Edit2 className="w-4 h-4" />
                                        </button>
                                        <button
                                            onClick={() => generateRequisitionPDF(req)}
                                            className="p-2 hover:bg-emerald-500/10 rounded-xl transition-all text-muted-foreground hover:text-emerald-600"
                                            title="Download PDF"
                                        >
                                            <Printer className="w-4 h-4" />
                                        </button>
                                        <button
                                            onClick={() => handleDelete(req.id)}
                                            className="p-2 hover:bg-rose-500/10 rounded-xl transition-all text-muted-foreground hover:text-rose-600"
                                            title="Delete"
                                        >
                                            <Trash2 className="w-4 h-4" />
                                        </button>
                                    </div>
                                </td>
                            </tr>
                        ))}
                    </tbody>
                </table>
            </div>

            {/* Requisition Detail Modal */}
            {selectedReq && (
                <div className="fixed inset-0 z-[100] flex items-center justify-center p-4">
                    <div className="absolute inset-0 bg-background/80 backdrop-blur-sm" onClick={() => setSelectedReq(null)} />
                    <div className="relative w-full max-w-3xl bg-card border border-border rounded-[3.5rem] shadow-2xl overflow-hidden animate-in fade-in zoom-in duration-300">
                        <div className="p-10 border-b border-border flex items-center justify-between bg-muted/20">
                            <div>
                                <h3 className="text-2xl font-black italic tracking-tight">{selectedReq.requisitionNumber}</h3>
                                <p className="text-[10px] font-black uppercase tracking-widest text-muted-foreground mt-1">{selectedReq.branch.name} • {format(new Date(selectedReq.date), 'PPPP')}</p>
                            </div>
                            <div className="flex items-center gap-4">
                                <StatusBadge status={selectedReq.status} />
                                <button onClick={() => setSelectedReq(null)} className="p-2 hover:bg-muted rounded-xl transition-colors">
                                    <XCircle className="w-5 h-5 text-muted-foreground" />
                                </button>
                            </div>
                        </div>
                        <div className="p-10">
                            <h4 className="text-[10px] font-black uppercase tracking-widest text-muted-foreground mb-6">Requested Materials</h4>
                            <div className="border border-border rounded-3xl overflow-hidden shadow-inner">
                                <table className="w-full text-left">
                                    <thead className="bg-muted/30 border-b border-border">
                                        <tr>
                                            <th className="px-6 py-4 text-[9px] font-black uppercase tracking-widest text-muted-foreground">Product</th>
                                            <th className="px-6 py-4 text-[9px] font-black uppercase tracking-widest text-muted-foreground">SKU</th>
                                            <th className="px-6 py-4 text-right text-[9px] font-black uppercase tracking-widest text-muted-foreground">Quantity</th>
                                        </tr>
                                    </thead>
                                    <tbody className="divide-y divide-border/50">
                                        {selectedReq.items.map((item, idx) => (
                                            <tr key={idx} className="hover:bg-muted/5">
                                                <td className="px-6 py-4 text-sm font-bold">{item.productName}</td>
                                                <td className="px-6 py-4 text-[10px] font-black text-muted-foreground uppercase">{item.sku || 'N/A'}</td>
                                                <td className="px-6 py-4 text-right text-sm font-black">{item.quantity}</td>
                                            </tr>
                                        ))}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                        <div className="p-10 pt-0 flex justify-end gap-4">
                            <button
                                onClick={() => generateRequisitionPDF(selectedReq)}
                                className="flex items-center gap-3 px-8 py-4 bg-primary text-white text-[10px] font-black uppercase tracking-widest rounded-3xl shadow-2xl shadow-primary/30 hover:shadow-primary/50 transition-all"
                            >
                                <Printer className="w-4 h-4" />
                                Print Official PDF
                            </button>
                        </div>
                    </div>
                </div>
            )}
        </div>
    );
};

function PriorityBadge({ priority }: { priority: Requisition['priority'] }) {
    const config = {
        LOW: { color: 'bg-slate-500/10 text-slate-600', label: 'Low' },
        NORMAL: { color: 'bg-blue-500/10 text-blue-600', label: 'Normal' },
        HIGH: { color: 'bg-orange-500/10 text-orange-600', label: 'High' },
        URGENT: { color: 'bg-rose-500/10 text-rose-600 animate-pulse', label: 'Urgent' },
    };
    const style = config[priority];
    return (
        <span className={`px-2.5 py-1 rounded-lg text-[10px] font-black uppercase tracking-wider ${style.color}`}>
            {style.label}
        </span>
    );
}

function StatusBadge({ status }: { status: Requisition['status'] }) {
    const config = {
        PENDING: { icon: Clock, color: 'text-amber-500 bg-amber-500/10', label: 'Pending' },
        APPROVED: { icon: CheckCircle2, color: 'text-blue-500 bg-blue-500/10', label: 'Approved' },
        FULFILLED: { icon: CheckCircle2, color: 'text-emerald-500 bg-emerald-500/10', label: 'Fulfilled' },
        REJECTED: { icon: XCircle, color: 'text-rose-500 bg-rose-500/10', label: 'Rejected' },
        CANCELLED: { icon: XCircle, color: 'text-slate-500 bg-slate-500/10', label: 'Cancelled' },
    };
    const style = config[status];
    const Icon = style.icon;
    return (
        <div className={`inline-flex items-center gap-1.5 px-2.5 py-1 rounded-lg ${style.color}`}>
            <Icon className="w-3 h-3" />
            <span className="text-[10px] font-black uppercase tracking-wider">{style.label}</span>
        </div>
    );
}
